# Generated by Django 3.1.4 on 2020-12-25 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_multiplier', models.FloatField(blank=True, null=True)),
                ('new_multiplier', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.vehicle')),
            ],
        ),
    ]
