# Generated by Django 3.1.4 on 2020-12-25 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_vehiclehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_cost_ac', models.FloatField(blank=True, null=True)),
                ('new_cost_ac', models.FloatField(blank=True, null=True)),
                ('old_cost_non_ac', models.FloatField(blank=True, null=True)),
                ('new_cost_non_ac', models.FloatField(blank=True, null=True)),
                ('old_cost_per_person', models.FloatField(blank=True, null=True)),
                ('new_cost_per_person', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.hotel')),
            ],
        ),
    ]
